// Auto-generated by scripts/deploy.ts on 2026-08-08T06:12:42.589Z. Do not edit by hand.

export const API_REGISTRY_ADDRESS = "0x343676948a62279c5a44d33e545dac90d467a0cf" as const;

export const API_REGISTRY_ABI = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_recorder",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "payer",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "priceMicro",
        "type": "uint256"
      }
    ],
    "name": "CallPaid",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "path",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "priceMicro",
        "type": "uint256"
      }
    ],
    "name": "EndpointRegistered",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "endpointCount",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      }
    ],
    "name": "getEndpoint",
    "outputs": [
      {
        "internalType": "string",
        "name": "path",
        "type": "string"
      },
      {
        "internalType": "uint256",
        "name": "priceMicro",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "callCount",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "globalCalls",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "owner",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "payer",
        "type": "address"
      }
    ],
    "name": "recordCall",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "recorder",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "path",
        "type": "string"
      },
      {
        "internalType": "uint256",
        "name": "priceMicro",
        "type": "uint256"
      }
    ],
    "name": "registerEndpoint",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_recorder",
        "type": "address"
      }
    ],
    "name": "setRecorder",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;
