import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { createPublicClient, createWalletClient, http } from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { compileApiRegistry } from "./compile";
import { EXPLORER_URL, RPC_URL, monadTestnet } from "../src/lib/chain";

function loadEnvLocal() {
  const envPath = resolve(process.cwd(), ".env.local");
  if (!existsSync(envPath)) return;
  const content = readFileSync(envPath, "utf8");
  for (const rawLine of content.split("\n")) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const eqIdx = line.indexOf("=");
    if (eqIdx === -1) continue;
    const key = line.slice(0, eqIdx).trim();
    let value = line.slice(eqIdx + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (!(key in process.env)) process.env[key] = value;
  }
}

const ENDPOINTS_TO_REGISTER: Array<{ path: string; priceMicro: bigint }> = [
  { path: "/api/summarize", priceMicro: BigInt(1000) },
  { path: "/api/sentiment", priceMicro: BigInt(1000) },
  { path: "/api/price", priceMicro: BigInt(2000) },
];

async function main() {
  loadEnvLocal();

  const privateKey = process.env.PRIVATE_KEY;
  if (!privateKey || !/^0x[0-9a-fA-F]{64}$/.test(privateKey)) {
    throw new Error(
      "PRIVATE_KEY missing or invalid in .env.local (expected 0x-prefixed 64 hex chars)",
    );
  }

  const account = privateKeyToAccount(privateKey as `0x${string}`);

  const publicClient = createPublicClient({
    chain: monadTestnet,
    transport: http(RPC_URL),
  });
  const walletClient = createWalletClient({
    account,
    chain: monadTestnet,
    transport: http(RPC_URL),
  });

  console.log(`Deployer: ${account.address}`);

  const balance = await publicClient.getBalance({ address: account.address });
  console.log(`Balance: ${balance} wei`);
  if (balance === BigInt(0)) {
    throw new Error(
      `Deployer ${account.address} has 0 MON on Monad Testnet. Fund it via the faucet before deploying.`,
    );
  }

  console.log("Compiling ApiRegistry.sol...");
  const { abi, bytecode } = compileApiRegistry();

  console.log("Deploying ApiRegistry (recorder = deployer)...");
  const deployHash = await walletClient.deployContract({
    abi,
    bytecode,
    args: [account.address],
  });
  const deployReceipt = await publicClient.waitForTransactionReceipt({
    hash: deployHash,
  });
  const contractAddress = deployReceipt.contractAddress;
  if (!contractAddress) {
    throw new Error("Deployment receipt did not include a contract address");
  }
  console.log(`Deployed at: ${contractAddress}`);
  console.log(`Explorer: ${EXPLORER_URL}/address/${contractAddress}`);

  for (const endpoint of ENDPOINTS_TO_REGISTER) {
    console.log(
      `Registering ${endpoint.path} (${endpoint.priceMicro} micro-USD)...`,
    );
    const hash = await walletClient.writeContract({
      address: contractAddress,
      abi,
      functionName: "registerEndpoint",
      args: [endpoint.path, endpoint.priceMicro],
    });
    const receipt = await publicClient.waitForTransactionReceipt({ hash });
    console.log(`  tx: ${EXPLORER_URL}/tx/${receipt.transactionHash}`);
  }

  const contractTsPath = resolve(process.cwd(), "src/lib/contract.ts");
  const contractTsContent = `// Auto-generated by scripts/deploy.ts on ${new Date().toISOString()}. Do not edit by hand.

export const API_REGISTRY_ADDRESS = "${contractAddress}" as const;

export const API_REGISTRY_ABI = ${JSON.stringify(abi, null, 2)} as const;
`;
  writeFileSync(contractTsPath, contractTsContent);
  console.log(`Saved address + ABI to ${contractTsPath}`);

  console.log("\nDone.");
  console.log(`Contract: ${EXPLORER_URL}/address/${contractAddress}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
